version: '3'
services:
  db:
    image: mysql:5.7.41
    hostname: ${dbdomain}.${host}
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${dbdomain}.${host}
    ports:
      - ${dbport}:${dbport}
    environment:
      MYSQL_ROOT_PASSWORD: ${dbpassword}
      MYSQL_USER: ${dbuser}
      MYSQL_PASSWORD: ${dbpassword}
      MYSQL_DATABASE: ${database}
    tty: true
  usi-grpc-service:
    image: ${service}
    hostname: ${domain}.${host}
    container_name: ${domain}.${host}
    ports:
      - ${port}:${port}
    environment:
      - DB_NAME=${database}
      - DB_SCHEME=${database}
      - DB_HOST=${dbdomain}.${host} 
      - DB_PORT=${dbport}
      - DB_USERNAME=${dbuser}
      - DB_PASSWORD=${dbpassword}
      - SERVICE_HOST=${domain}.${host}
      - SERVICE_PORT=${port}
    depends_on:
      - db
    tty: true
networks:
  backend:
    driver: bridge