// service.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: model/protofile/login.proto

package login

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	USI_Login_FullMethodName = "/USI/Login"
)

// USIClient is the client API for USI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type USIClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type uSIClient struct {
	cc grpc.ClientConnInterface
}

func NewUSIClient(cc grpc.ClientConnInterface) USIClient {
	return &uSIClient{cc}
}

func (c *uSIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, USI_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// USIServer is the server API for USI service.
// All implementations must embed UnimplementedUSIServer
// for forward compatibility
type USIServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedUSIServer()
}

// UnimplementedUSIServer must be embedded to have forward compatible implementations.
type UnimplementedUSIServer struct {
}

func (UnimplementedUSIServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUSIServer) mustEmbedUnimplementedUSIServer() {}

// UnsafeUSIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to USIServer will
// result in compilation errors.
type UnsafeUSIServer interface {
	mustEmbedUnimplementedUSIServer()
}

func RegisterUSIServer(s grpc.ServiceRegistrar, srv USIServer) {
	s.RegisterService(&USI_ServiceDesc, srv)
}

func _USI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(USIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: USI_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(USIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// USI_ServiceDesc is the grpc.ServiceDesc for USI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var USI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "USI",
	HandlerType: (*USIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _USI_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model/protofile/login.proto",
}
